### ISSUE TITLE
White bar along the top of desktop

### ISSUE THREAD

**Issue by LiamDawe** [system76/pop-gtk-theme#17] opened 2017-05-09 09:22 UTC
```
 * Distribution - Ubuntu 17.04
 * Gtk+ 3.0 version - latest available
 * Desktop environment - GNOME Shell
 ```

In Ubuntu 17.04 with GNOME Shell if you have the GTK Pop theme either variants and desktop icons enabled, the desktop wallpaper seems to get a white bar going along the top of the screen. Maximised windows cover it, it's only the desktop view itself.

Other themes are not affected.

**Comment by isantop** [comment] 2017-05-10 05:19
Thanks for opening this issue! Can you send in a screenshot showing the problem? I'm not quite sure what precisely you're seeing since I don't seem to have this problem on my machine.

**Comment by jabk** [comment] 2017-05-15 00:31
Same problem!
* Distribution: Ubuntu 17.04
* GTK version: 3.22.11-0ubuntu3
* Desktop environment: GNOME Shell

Screenshot: http://imgur.com/a/45b7q

**Comment by isantop** [comment] 2017-05-15 16:46
I still can't seem to reproduce this issue. I think it may be a bug in Nautilus. Can you guys post the output of `apt policy nautilus`

![screenshot from 2017-05-15 10-45-35](https://cloud.githubusercontent.com/assets/5883565/26068750/cc163c5e-395b-11e7-9dfb-e81e7ce4c369.png)

**Comment by isantop** [comment] 2017-05-30 21:05
Can't reproduce issue, at incomplete stage for 15+ days. Closing.

**Closed by isantop** 2017-05-30 21:05 UTC
Labels: Incomplete
