### ISSUE TITLE
Comboboxes animate and are misaligned when first rendered

### ISSUE THREAD

**Issue by cassidyjames** [system76/pop-gtk-theme#6] opened 2017-04-28 20:08 UTC
**Reporter info**

 ```
 * Distribution - Ubuntu GNOME 17.04
 * Gtk+ 3.0 version - 3.24
 * Desktop environment - GNOME Shell
 ```

**Related Application and/or Shell theming (or name of widget)**
GTK3 comboboxes

**Actual issue**
When opening a GTK3 combobox for the first time, the menu animates in and then is misaligned from the combobox widget itself. Closing and reopening the widget does not animate, and corrects the alignment.

**Comment by cassidyjames** [comment] 2017-04-28 20:22
![gif](https://cloud.githubusercontent.com/assets/611168/25545945/1492f29c-2c1e-11e7-9038-49a794df4d2e.gif)

**Comment by isantop** [comment] 2017-05-03 20:21
Bug is a duplicate of the upstream Adapta bug

**Closed** 2017-05-03 21:54 UTC
