### ISSUE TITLE
GNOME Dash Window overview close button slight distortion when hovering on

### ISSUE THREAD

**Issue by Feichtmeier** [system76/pop-gtk-theme#20] opened 2017-08-29 10:56 UTC
**NOTE: Before reporting a bug, please check whether it also occurs with other themes.**
> If the bug also occurs with other themes (especially upstream default theme),
it is very likely an upstream issue.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
**Reporter info**

```
 * Distribution - Ubuntu 17.10 GNOME
 * Gtk+ 3.0 version - 3.22
 * Desktop environment - GNOME
 * Pop version - 2.1.1.8

 ```

**Related Application and/or Shell theming (or name of widget)**
GNOME shell

**Actual issue**
When you hover over the close button of a window in the GNOME dash window overview the button is slightly distorted. I've recorded a video for the sake of it =)

https://drive.google.com/file/d/0BweBBOYdSgGIUUE1aFRvQ0dJNXM/view?usp=drivesdk
(download it, in chrome it looks very low res)
**Steps to reproduce**

**Expected behavior**

**Behavior in Adwaita**

**Other Note (feature-request, question, etc...)**

**Comment by isantop** [comment] 2017-08-30 15:58
Marking this as `help-wanted` so that someone else can test on 17.04. My machine is on 17.10.

**Comment by mozartilize** [comment] 2017-08-31 02:49
I'm using ubuntu gnome 17.04 and have this issue too

**Comment by Feichtmeier** [comment] 2017-09-02 08:03
I tried it in a VM with 17.10 and there the issue does not occure. So maybe you can just ignore it since 17.04 won't be supported for long anyways =)

**Comment by isantop** [comment] 2017-10-03 19:00
I can't seem to reproduce this issue in 17.10. Can you try it again and see if it's still an issue? Part of me thinks this is an issue with GNOME Shell rendering (of which there are a few)

**Comment by isantop** [comment] 2017-10-03 20:01
I've seen this replicated on Intel graphics systems. However, it's not present on Nvidia machines. Since there's no nvidia or intel specific code present in the theme, we can therefore be extremely certain labeling this as a GNOME Shell rendering bug. Thanks for the report though!

**Closed by isantop** 2017-10-03 20:01 UTC
Labels: bug, help wanted
